import type { Metadata } from 'next'
import { Lilita_One } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import { cn } from '@/lib/utils'

const font = Lilita_One({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
	title: 'Github Branch',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{ children: ReactNode }>) {
	return (
		<html lang="pt-BR">
			<body className={cn('antialiased', font.className)}>{children}</body>
		</html>
	)
}
